# BlockVerse Docker Compose
# One-command deployment: docker-compose up

version: '3.8'

services:
  blockverse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blockverse-app
    ports:
      - "3000:3000"
    volumes:
      # Persist SQLite database
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Generate a random JWT secret or provide your own
      - JWT_SECRET=${JWT_SECRET:-change-me-in-production}
      - VITE_APP_TITLE=${VITE_APP_TITLE:-BlockVerse}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

# Volumes for persistent data
volumes:
  blockverse-data:
    driver: local
